### ISSUE TITLE
Incorrect Arguments Error

### ISSUE THREAD

**Issue by akhanolk** [cmu-is-projects/ferry_demo#3]
I have attached a screenshot of the error below:

 
(https://cloud.githubusercontent.com/assets/7462762/7222128/54267892-e6d5-11e4-83ac-0aa44bdb5007.png)

**Comment by anthcor** [comment]
check to make sure that its resolved in https://github.com/cmu-is-projects/ferry/pull/106

if you bundle update version 1.3.2 should have the fix - let me know!
